# Generated by Django 4.2.6 on 2023-10-13 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('name', models.CharField(max_length=120)),
                ('count', models.IntegerField()),
                ('job_category', models.CharField(choices=[('All Category', 'All Category'), ('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3'), ('Category 4', 'Category 4')], max_length=15)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=15)),
                ('job_location', models.CharField(choices=[('All Category', 'All Category'), ('Category 1', 'Category 1'), ('Category 2', 'Category 2'), ('Category 3', 'Category 3'), ('Category 4', 'Category 4')], max_length=15)),
                ('Experience', models.CharField(choices=[('1-2 Years', '1-2 Years'), ('2-3 Years', '2-3 Years'), ('3-6 Years', '3-6 Years'), ('6-more', '6-more')], max_length=100)),
                ('Posted_Within', models.CharField(choices=[('Any', 'Any'), ('Today', 'Today'), ('Last 2 days', 'Last 2 days'), ('Last 3 days', 'Last 3 days'), ('Last 5 days', 'Last 5 days'), ('Last 10 days', 'Last 10 days')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.TextField(max_length=1000)),
                ('web_site', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='job')),
                ('job_locetion', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('rounding_salary', models.CharField(max_length=100)),
                ('job_Description', models.TextField(max_length=10000)),
                ('repuired_knowledge', models.TextField(max_length=10000)),
                ('experience', models.TextField(max_length=10000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='job.company')),
                ('job_Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_job', to='job.category')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Posted_date', models.DateTimeField()),
                ('locetion', models.CharField(max_length=50)),
                ('Vacancy', models.IntegerField()),
                ('salary', models.CharField(max_length=100)),
                ('Application_date', models.CharField(max_length=100)),
                ('job_natur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_time', to='job.job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='overview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_overview', to='job.job_overview'),
        ),
    ]
