# Generated by Django 4.2.6 on 2023-10-14 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.TextField(max_length=1000)),
                ('web_site', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='job')),
                ('job_locetion', models.CharField(max_length=100)),
                ('agency', models.CharField(max_length=100)),
                ('rounding_salary', models.CharField(max_length=100)),
                ('job_Description', models.TextField(max_length=10000)),
                ('Experience', models.TextField(max_length=10000)),
                ('Vacancy', models.IntegerField()),
                ('salary_year', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='job.company')),
                ('job_Art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_job', to='job.category')),
            ],
        ),
    ]
