# Generated by Django 4.2.6 on 2023-10-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_overview',
            old_name='salary',
            new_name='salary_year',
        ),
        migrations.AlterField(
            model_name='job_overview',
            name='job_natur',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=15),
        ),
    ]
