# Generated by Django 4.2.6 on 2023-10-14 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_rename_salary_job_overview_salary_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_overview',
            name='job_natur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_jobart', to='job.category'),
        ),
    ]
