# Generated by Django 4.2.6 on 2023-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_overview_job_natur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Posted_Within',
        ),
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='category',
            name='job_type',
        ),
        migrations.AlterField(
            model_name='job_overview',
            name='job_natur',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Remote', 'Remote'), ('Freelance', 'Freelance')], max_length=15),
        ),
    ]
