# Generated by Django 4.2.6 on 2023-10-14 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_category_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='Experience',
        ),
        migrations.RemoveField(
            model_name='job',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='job',
            name='repuired_knowledge',
        ),
        migrations.AddField(
            model_name='job',
            name='Vacancy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_year',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Job_Overview',
        ),
    ]
